[tools]
bat = "0.26.1"
btop = "1.4.6"
difftastic = "0.68.0"
dust = "1.2.4"
eza = { version = "0.23.4", postinstall = "fetch-completions-github eza eza-community/eza \"$(basename \"$MISE_TOOL_INSTALL_PATH\")\" \"completions-$(basename \"$MISE_TOOL_INSTALL_PATH\").tar.gz\" \"*/_eza\"" }
fd = "10.4.2"
fzf = "0.72.0"
hexyl = "0.17.0"
jless = "0.9.0"
jq = "1.8.1"
neovim = "0.12.2"
numbat = "1.23.0"
ripgrep = "15.1.0"
sd = "1.1.0"
shellcheck = "0.11.0"
"cargo:tokei" = "14.0.0"
tree-sitter = "0.26.8"
usage = "3.2.1"
uv = "0.11.8"
