[tools]
node = [ "latest", "lts", "24", "22", "20", "18" ]
opentofu = "latest"
cosign = "latest"
gh = "latest"

[env]
MISE_NODE_COREPACK = "true"

[settings]
idiomatic_version_file_enable_tools = ["node"]
